import "DashboardViewModel.idl";
namespace EtherealScepter
{
    runtimeclass App : Microsoft.UI.Xaml.Application
    {
        App();

        EtherealScepter.ViewModels.DashboardViewModel DashboardViewModel{ get; };
    }
}
