import "Models.PortMappingInfo.idl";
namespace EtherealScepter.ViewModels
{
    runtimeclass PortPageViewModel : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        PortPageViewModel();

        Windows.Foundation.Collections.IObservableVector<EtherealScepter.Models.PortMappingInfo>
            PortMappings{ get; };

        void AddMapping(EtherealScepter.Models.PortMappingInfo mapping);
        void RemoveMapping(EtherealScepter.Models.PortMappingInfo mapping);
    }
}