import "UpnpViewModel.idl";
namespace EtherealScepter
{
    [default_interface]
    runtimeclass UPnPPage : Microsoft.UI.Xaml.Controls.Page
    {
        UPnPPage();
        EtherealScepter.ViewModels.UpnpViewModel ViewModel{ get; };
    }
}
