namespace EtherealScepter.Models
{
    runtimeclass UpnpDeviceItem
    {
        String Location;
        String FriendlyName;
        String Manufacturer;
        String ModelName;
        Boolean IsIgd;

        Microsoft.UI.Xaml.Visibility IgdVisibility{ get; };
    }
}
