import "NetworkPageViewModel.idl";

namespace EtherealScepter {
[default_interface] runtimeclass NetworkPage : Microsoft.UI.Xaml.Controls.Page {
  NetworkPage();
  EtherealScepter.ViewModels.NetworkPageViewModel ViewModel{ get; };
}
} // namespace EtherealScepter
